### ISSUE TITLE
Decoder?

### ISSUE THREAD

**Issue by Thanh-Binh** [cbachhuber/CppVideoStreamer#1]
Hi I want to use your code, but need a decoder by receiver.
Could you please share it for us? Thanks

**Comment by cbachhuber** [comment]
I had used [this code](https://github.com/cbachhuber/CppVideoStreamer/files/7920871/VideoPlayer.zip) back in the day. It does the job and plays the video with a low latency.

Warning: It is badly written and documented, however.

If you want to save yourself the trouble of setting this up, you can also just use [ffplay](https://www.ffmpeg.org/ffplay.html) for decoding and playback. That has a few more frames latency though, if I remember correctly.

**Comment by Thanh-Binh** [comment]
Thanks

**Comment by cbachhuber** [comment]
This has been again brought up in #4. I've now included a low latency decoder as part of this repo, see [this comment](https://github.com/cbachhuber/CppVideoStreamer/issues/4#issuecomment-1677680032).
