### ISSUE TITLE
Reciver Client insted of ffplay

### ISSUE THREAD

**Issue by amerghazal7** [cbachhuber/CppVideoStreamer#4]
Hello, I just wanted to ask if there's a way or documentation to develop a C++ consumer for this stream instead of ffplay because it's causing too much delay and I want to access to the received frames so I can do further applications not just showing it.

**Comment by cbachhuber** [comment]
Hi! I also faced the delay problem, so I wrote my own player. I found the ancient code that I worked with back in Uni days and pushed it in [this commit](https://github.com/cbachhuber/CppVideoStreamer/commit/0fcf9055e8785d5e7d0a0e4ceafa7d88ad939b24) to this repo.

It's building when I install `libsdl2-dev` (added to readme). Does that work for you? It might need modifications for your use case.

**Comment by aihamshikhomicro** [comment]
Thanks a lot!

**Comment by cbachhuber** [comment]
Welcome! I'm closing this issue. Let me know if anything else needs to be done 👍
